"""empty message

Revision ID: 48e1135a8cd6
Revises: cb86713c729d
Create Date: 2019-08-14 17:47:57.045010

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '48e1135a8cd6'
down_revision = 'cb86713c729d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('question_id', sa.Integer(), nullable=True))
    op.drop_constraint('answer_ibfk_1', 'answer', type_='foreignkey')
    op.create_foreign_key(None, 'answer', 'question', ['question_id'], ['id'])
    op.drop_column('answer', 'answer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('answer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.create_foreign_key('answer_ibfk_1', 'answer', 'question', ['answer_id'], ['id'])
    op.drop_column('answer', 'question_id')
    # ### end Alembic commands ###
